### ISSUE TITLE
docs: TYPE YOUR QUESTION HERE

### ISSUE THREAD

**Issue by aditjacko** [canonical/ubuntu-packaging-guide#44]
*Please describe the question or issue you're facing with "Filesystem Hierarchy Standard (FHS) - Ubuntu Packaging Guide".*

---
*Reported from: https://canonical-ubuntu-packaging-guide.readthedocs-hosted.com/en/latest/reference/filesystem-hierarchy-standard.html*

**Comment by dviererbe** [comment]
@aditjacko can you describe how we can help you? You haven't added any details regarding your question or issue.

Note: The [Filesystem Hierarchy Standard (FHS)](https://canonical-ubuntu-packaging-guide.readthedocs-hosted.com/en/latest/reference/filesystem-hierarchy-standard.html) page on which you reported this issue is not complete yet. We currently overhaul the packaging guide and therefore the content for many pages isn't written yet. We intend to complete an initial version with the Ubuntu 24.04 LTS release.

**Comment by dviererbe** [comment]
@aditjacko I will close this issue now, because of inactivity. Feel free to respond with a comment and I will reopen the bug ticket again; or create a new bug ticket.
