### ISSUE TITLE
docs: the en/latest/tutorial/* pages text is almost empty

### ISSUE THREAD

**Issue by shlomif** [canonical/ubuntu-packaging-guide#67]
The text in the pages is empty (in firefox on fedora 40 at least). I was referred to these pages from https://help.launchpad.net/Packaging/PPA/Uploading 

---
*Reported from: https://canonical-ubuntu-packaging-guide.readthedocs-hosted.com/en/latest/tutorial/getting-set-up/*

**Comment by dviererbe** [comment]
@shlomif thank you for taking the time to report this and helping to make the Ubuntu packaging guide better. The guide is currently undergoing a major overhaul to bring it up to date. The current state you are seeing now is a preview of this effort. The empty tutorial is just a placeholder and will eventually be replaced. Therefore this issue is already on our Roadmap.
